####################################################################################################
# Backend
####################################################################################################
backend:
  name: github
  repo: pmpinto/personal-website
  branch: master
  site_domain: pedropinto.me
  base_url: https://api.netlify.com
  auth_endpoint: auth
  squash_merges: true
  commit_messages:
    create: 'content: Create {{collection}} “{{slug}}”'
    update: 'content: Update {{collection}} “{{slug}}”'
    delete: 'content: Delete {{collection}} “{{slug}}”'
    uploadMedia: 'content: Upload “{{path}}”'
    deleteMedia: 'content: Delete “{{path}}”'
    openAuthoring: 'content: {{message}}'

####################################################################################################
# Media
####################################################################################################
media_folder: src/static_assets/images/uploads
public_folder: /static_assets/images

####################################################################################################
# Misc
####################################################################################################
publish_mode: editorial_workflow
site_url: https://pedropinto.me
# logo_url: /images/logo.svg

##################################################################################################
# Aliases
##################################################################################################
aliases:
  fields:
    - &FIELD_BLURB
      label: 'Blurb'
      name: 'blurb'
      widget: 'string'

    - &FIELD_BODY
      name: 'body'
      label: 'Body'
      widget: 'markdown'

    - &FIELD_DATE
      label: 'Date'
      name: 'date'
      widget: 'datetime'
      date_format: YYYY-MM-DD
      time_format: HH:mm:ss ZZ
      format: YYYY-MM-DDTHH:mm:ssZZ
      picker_utc: false

    - &FIELD_TITLE
      name: 'title'
      label: 'Title'
      widget: 'string'


####################################################################################################
# Collections
####################################################################################################
collections:
  ##################################################################################################
  ## Collection: Site configs
  ##################################################################################################
  - name: siteConfigs
    label: ⚙️ Configs
    files:
      - name: navigation
        label: 👉 Navigation
        file: src/_data/navigation.json
        editor:
          preview: false
        fields:
          - name: links
            label: Links
            label_singular: link
            widget: list
            fields:
              - name: label
                label: Label
                widget: string
              - name: url
                label: URL
                widget: string

  ##################################################################################################
  ## Collection: History
  ##################################################################################################
  - name: history
    label: 📜 The History
    label_singular: History Event
    folder: src/history
    preview_path: 'history/'
    description: 'Life events. | Can be seen at pedropinto.me/history'
    summary: "{{date | date('YYYY')}} — {{title}}"
    create: true
    sortable_fields:
      - 'date'
      - 'title'
    fields:
      - <<: *FIELD_TITLE

      - <<: *FIELD_DATE
        time_format: false

      - <<: *FIELD_BODY

  ##################################################################################################
  ## Collection: Designer
  ##################################################################################################
  - name: designer
    label: 👨🏻‍🎨 The Designer
    folder: src/designer
    create: true
    fields:
      - name: title
        label: Title
        widget: string

  ##################################################################################################
  ## Collection: Photographer
  ##################################################################################################
  - name: photographer
    label: 📷 The Photographer
    folder: src/photographer
    create: true
    identifier_field: date
    fields:
      - name: date
        label: Date
        widget: date
      - name: image
        label: Image
        widget: image

  ##################################################################################################
  ## Collection: Writer
  ##################################################################################################
  - name: writer
    label: ✍️ The Writer
    folder: src/blog
    create: true
    fields:
      - name: title
        label: Title
        widget: string
