####################################################################################################
# Backend
####################################################################################################
backend:
  name: github
  repo: pmpinto/personal-website
  branch: master
  site_domain: pedropinto.me
  base_url: https://api.netlify.com
  auth_endpoint: auth
  squash_merges: true
  commit_messages:
    create: 'content: Create {{collection}} “{{slug}}”'
    update: 'content: Update {{collection}} “{{slug}}”'
    delete: 'content: Delete {{collection}} “{{slug}}”'
    uploadMedia: 'content: Upload “{{path}}”'
    deleteMedia: 'content: Delete “{{path}}”'
    openAuthoring: 'content: {{message}}'

####################################################################################################
# Media
####################################################################################################
media_folder: src/static_assets/images
public_folder: /static_assets/images

####################################################################################################
# Misc
####################################################################################################
publish_mode: editorial_workflow
site_url: https://pedropinto.me
# logo_url: /images/logo.svg


####################################################################################################
# Collections
####################################################################################################
collections:
  ##################################################################################################
  ## Collection: Site configs
  ##################################################################################################
  - name: siteConfigs
    label: Configs
    files:
      - name: navigation
        label: Navigation
        file: src/_data/navigation.json
        fields:
          - name: label
            label: Label
            widget: string
          - name: url
            label: URL
            widget: string

  ##################################################################################################
  ## Collection: Photographer
  ##################################################################################################
  - name: photographer
    label: Photographer
    folder: src/photographer
    create: true
    identifier_field: date
    fields:
      - name: date
        label: Date
        widget: date
      - name: image
        label: Image
        widget: image
